### ISSUE TITLE
Start condition

### ISSUE THREAD

**Issue by dbartel** [arielfaur/ionic-wizard#12]
It'd be nice if there was a ``start-condition`` that had to be fulfilled for the ionWizardStart similar to the next/previous conditions

I might do a pull request for this sometime this weekend if I have time

**Comment by arielfaur** [comment]
That's indeed a cool feature. Should be fairly simple. I will add it when I am done merging your other pull request :+1:

**Comment by dbartel** [comment]
sounds good, thanks
