### ISSUE TITLE
Strange UI issue on Tab

### ISSUE THREAD

**Issue by niyando** [arielfaur/ionic-wizard#16]
Hi @arielfaur,
Found a strange UI issue where pressing tabs while filling out a form breaks the slidebox.

I am able to reproduce this on your demo plunkr
http://plnkr.co/edit/V3AiSnB4WYIXmCbNkBvn?p=preview

Steps:
1) Click on next to go to second screen
2) Focus on 'Type something' input box to type something.
3) Tab on keyboard.

**Comment by arielfaur** [comment]
@niyando I believe this is the expected behavior on a desktop browser. Mobile devices don't have a tab key :-)
Are you building a web app with Ionic?

**Comment by niyando** [comment]
Not exactly a web app but using it as mobile website + native app. There is a `>` button  on accessory bar on top of keyboard to tab through inputs.

Anyways, I was able to solve this by disabling form elements of all slides except the active slide. 
https://github.com/driftyco/ionic/issues/4346#issuecomment-147295322

Closing this :)
