### ISSUE TITLE
long content doesn't scroll

### ISSUE THREAD

**Issue by b0unc3** [arielfaur/ionic-wizard#2]
Hi,

the problem here is that if you have a long content inside a ion-slide ion-wizard element it doesn't scroll. If you add a ion-scroll tag, the conditional steps get lost.
I'll appreciate any hints about it.
Thanks.

**Comment by arielfaur** [comment]
Do you happen to have a codepen or a project to share so I can test it? I wil try to reproduce your use case.

**Comment by arielfaur** [comment]
OK, I found the issue and the solution is to wrap your content with a `ion-content` directive to enable scrolling within the slide.  Try the following the code: create a `ion-content` inside the `ion-slide` and apply the `has-header` class to the inner `ion-content` element, rather than the top element. 
Let me know if that works.

    <ion-slide-box ion-wizard>
        <ion-slide ion-wizard-step>
            <ion-content class="has-header">
            <div class="row">
                ...your long content here...
            </div>
            <div class="row">
                ...your long content here...
            </div>
            </ion-content>
        </ion-slide>
    </ion-slide-box>

**Comment by arielfaur** [comment]
Here's a working example:
http://run.plnkr.co/plunks/E6fpAnDtsxPAhhSCrNZ4/

**Comment by b0unc3** [comment]
maybe I wasn't clear enough.
Try to put the 'long content' in a section with a condition (like the second step in your) and you'll reproduce the issue.
example:
http://embed.plnkr.co/jLUNEY7Nnw1zbTUz8EhC/

Thanks.

**Comment by arielfaur** [comment]
@b0unc3 sorry I misread your first message! You were right, the condition did not work. I have fixed it and it seems to work now. For that to work I needed to create a new directive that enables scrolling within a slide (it is basically a fork of Ionic's `ion-content`).
Please check the updated demo link and documentation. You basically need to replace your `ion-content` with `ion-wizard-content`. The new version v1.0.3 is available on bower already.
Looking forward to your feedback!

**Comment by b0unc3** [comment]
Hi @arielfaur 
I've just tested the new version, and it is working like a charm, also with long content of course.
Thank you so much for your help and the very quick update!
I appreciate!
