### ISSUE TITLE
Is next-condition checked for the first slide?

### ISSUE THREAD

**Issue by oskarnrk** [arielfaur/ionic-wizard#20]
If I set next-condition for the first slide (a variable has to be not null to go forward) the Next button is still active and works. So I tap it, I go to the next slide and then I go back: now the button becomes disabled.
For your knowledge, the wizard is the first view I have opening the app.

**Comment by arielfaur** [comment]
Are you using the newer version 2.0 with Ionic 1.2 ?

**Comment by oskarnrk** [comment]
Yes, exactly. What I missed? :)

**Comment by arielfaur** [comment]
You're right. It's a bug. Thanks!

**Comment by arielfaur** [comment]
@oskarnrk I think I fixed this issue. Check release v2.0.1 please and let me know.
Thanks!

**Comment by oskarnrk** [comment]
@arielfaur the problem il solved in 2.0.1. Thank you!
