### ISSUE TITLE
When condition of next step is false, ion-wizard-next elements should be (optionally) disabled

### ISSUE THREAD

**Issue by nonplus** [arielfaur/ionic-wizard#5]
It would be nice if we could disable the `ion-wizard-next` button when the condition for the next step resolves to `false`.

This could either be the default behavior, or the wizard could add a, say, `$wizardNextCondition` property to the scope which could be then used in the template like so:
```
<ion-nav-buttons side="right">
    <button class="button button-stable no-animation" ion-wizard-next
        ng-disabled="!$wizardNextCondition">Next</button>
    <button class="button button-stable no-animation" ion-wizard-start="done()">OK</button>
</ion-nav-buttons>
```

**Comment by arielfaur** [comment]
Sounds like a good idea. I will look into it. Thanks!

**Comment by nonplus** [comment]
Let me know which approach you favor, and I should be able to get you a PR.

**Comment by arielfaur** [comment]
I tried a simple approach but there are some difficulties. I might need to refactor the module to make the ```ion-wizard``` directive a top directive surrounding the wizard buttons. Otherwise it gets tricky to access to button directives to take control.
I don't have time right now, but if you want to look into it go ahead! Pull requests are always welcome :)

**Comment by nonplus** [comment]
Which approach do you favor?  Having `ion-wizard-next` automatically disabled when next condition is falsy, or exposing a `$wizardNextCondition` on the scope within `ion-wizard-step`?

**Comment by arielfaur** [comment]
I think we could disable it by default if condition is falsy. What do you think?

**Comment by nonplus** [comment]
If it's automatically disabled, you would no longer be able to use the `$scope.$on('wizard:StepFailed')` event handler to tell the user why they can't advance to the next slide, since they wouldn't be able to click on the Next button.  FWIW, this isn't an issue for me - since I prefer the disabled button.

**Comment by dbartel** [comment]
I'm working on this currently - right now have a version that disables buttons how @nonplus described

I could write a config provider that sets whether the buttons get disabled for condition failure if we want to keep the ```$scope.$on('wizard:StepFailed')``` functionality

**Comment by arielfaur** [comment]
That's a good observation @nonplus. I guess then the other approach is better!
