### ISSUE TITLE
Help needed to restart the wizard from 1st slide

### ISSUE THREAD

**Issue by ganeshmgaikwad** [arielfaur/ionic-wizard#7]
Hi,

First of all, great solution for common business need.

In my use case, the user may need to revisit the wizard after moving to main application.

I tried doing following , but the wizard opens at last slide instead of first slide.

1. In the "playlists.html", inserted one button, labelled "Restart Wizard", & added ng-click attribute with new method as "ShowWiz()".
2. In the "PlaylistsCtrl", added the new method as below

$scope.ShowWiz = function() {
      $state.go('wizard.intro');
  };
3. This shows the last slide of wizard.

Please visit "http://plnkr.co/edit/pyQvKesSDVcuODOSSRLV?p=preview" link for demo.

I also need to pass captured values during wizard to main application. Is it possible without using $rootScope object.

May be I am missing something.

Thanks in advance.

Ganesh Gaikwad

**Comment by arielfaur** [comment]
Hi! I have added something to your Plunker. Check it out:
http://plnkr.co/eMEMOpCAHRStcIqRqsRF?p=info

You basically need to add something to the controller to restart the wizard from slide 0.
As far as wizard values are concerned you will need some persistence layer. I would look into localStorage to save temporary values.

**Comment by ganeshmgaikwad** [comment]
Hi,

Thanks a lot for quick response.

Is it possible to jump to specific slide, based on user response ?

E.g. The first slide may ask for gender, if the user selects "Male" he may be navigated to 2nd slide, if the user responds as "Female", she is directed to 3rd slide.

Thanks again.

Ganesh Gaikwad

**Comment by arielfaur** [comment]
I guess that would be a nice feature to implement, but would take some time. The module would need to collect and keep track of user input. 
At the moment what you can do is use the ```$ionicSlideBoxDelegate``` interface to navigate the slides. One solution would be to namespace your scope variables like ```$scope.step1.name``` or ```$scope.step2.age``` so you know which slide data belongs to. Then you could switch slides accordingly using ```$ionicSlideBoxDelegate.slide(n)``` based on your scope variables.
Would that work?

**Comment by ganeshmgaikwad** [comment]
Hi,

Sorry for delay in reply.

Will try the way you have shown, for time being.

I have also done a slight change in ion-wizard module, by changing "conditionFn: '&condition'" line to "conditionFn: '=condition'". This helped to specify the condition as function in the controller instead of single modal property to continue to next step. If the function returns true, the user is navigated to next step, if it returns false, user is kept on the current step.

Hope this will help someone.

Thanks again,

Ganesh Gaikwad
